title: Remote Sensing the Social Sciences - Fall 2022
author:
  name: benamie
  email: elinor@vt.edu
description: > # this means to ignore newlines until "show_excerpts:"
This page covers labs for the Virginia Tech graduate level course Remote Sensing in the Social Sciences (AAEC 5544), 
taught in the Fall 2022 by [Prof Elinor Benami](https://www.ebenami.com/) and TAed by [Ozzy Campos](https://rsigep.frec.vt.edu/students.html).
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

